### PR TITLE
Add json mapper for pp_ast

### PR DESCRIPTION
**Pull request by pedrobslisboa**
## Description

Add `json` mapper on `pp_ast` to improve usage in tools such as AST Explorer.
The idea is to increment the @NathanReb PR https://github.com/ocaml-ppx/ppxlib/pull/517

@NathanReb, your opinion on how to structure it better is very welcome.
@jchavarri @davesnx thank you for the help.

## How

To use it we just need to pass `--json` to `ppxlib-pp-ast`. It works with all other flags, such as `--show-attrs` and `--show-loc`.

### CODE REVIEW

**Comment by NathanReb** [comment]
Thanks @pedrobslisboa for working on this! I'm just about to merge ocaml-ppx#517. Would you mind opening this as a new PR upstream directly once it's done?

We can discuss this feature there then but I think it would be a great addition!

**Comment by pedrobslisboa** [comment]
> Thanks @pedrobslisboa for working on this! I'm just about to merge [ocaml-ppx#517](https://github.com/ocaml-ppx/ppxlib/pull/517). Would you mind opening this as a new PR upstream directly once it's done?
> 
> We can discuss this feature there then but I think it would be a great addition!

Sure

**Comment by pedrobslisboa** [comment]
Closing to continue it on ppxlib

**Comment by pedrobslisboa** [comment]
@NathanReb Sorry, I forgot to link the PR here.

For those who are interested: https://github.com/ocaml-ppx/ppxlib/pull/526

**Pull request closed without merging**
